##Reading the data

In [1]:
import pandas as pd
df=pd.read_excel('TradeDataWhole.xlsx')

In [2]:
df.head()

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20130101,2013,52,2013,699,IND,India,M,...,NaN,False,NaN,False,963315872.0,NaN,963315872.0,0,True,False
1,C,A,20130101,2013,52,2013,699,IND,India,M,...,NaN,False,NaN,False,22011508.0,NaN,22011508.0,0,True,False
2,C,A,20130101,2013,52,2013,699,IND,India,M,...,NaN,False,NaN,False,81995028.0,NaN,81995028.0,0,True,False
3,C,A,20130101,2013,52,2013,699,IND,India,M,...,NaN,False,NaN,False,41534.0,NaN,41534.0,0,True,False
4,C,A,20130101,2013,52,2013,699,IND,India,M,...,NaN,False,NaN,False,63834674.0,NaN,63834674.0,0,True,False

In [3]:
df.shape

(120, 47)

In [4]:
df.dtypes

typeCode                     object
freqCode                     object
refPeriodId                   int64
refYear                       int64
refMonth                      int64
period                        int64
reporterCode                  int64
reporterISO                  object
reporterDesc                 object
flowCode                     object
flowDesc                     object
partnerCode                   int64
partnerISO                   object
partnerDesc                  object
partner2Code                  int64
partner2ISO                  object
partner2Desc                 object
classificationCode           object
classificationSearchCode     object
isOriginalClassification       bool
cmdCode                       int64
cmdDesc                      object
aggrLevel                     int64
isLeaf                         bool
customsCode                  object
customsDesc                  object
mosCode                       int64
motCode                       int64
motDesc                      object
qtyUnitCode                   int64
qtyUnitAbbr                  object
qty                         float64
isQtyEstimated                 bool
altQtyUnitCode                int64
altQtyUnitAbbr               object
altQty                      float64
isAltQtyEstimated              bool
netWgt                      float64
isNetWgtEstimated              bool
grossWgt                    float64
isGrossWgtEstimated            bool
cifvalue                    float64
fobvalue                    float64
primaryValue                float64
legacyEstimationFlag          int64
isReported                     bool
isAggregate                    bool
dtype: object

###Selecting only necessary columns

In [5]:
cols=['refYear', 'partnerDesc', 'cmdCode', 'cifvalue']
df_clean=df[cols].copy()
df_clean.head()

   refYear    partnerDesc  cmdCode     cifvalue
0     2013          China     8541  963315872.0
1     2013  Rep. of Korea     8541   22011508.0
2     2013      Singapore     8541   81995028.0
3     2013       Viet Nam     8541      41534.0
4     2013            USA     8541   63834674.0

In [6]:
df_clean.columns= ['Year', 'Partner', 'Code', 'USD_Value_bn']
df_clean= df_clean.replace('Rep. of Korea', 'South Korea')
df_clean.head()

   Year      Partner  Code  USD_Value_bn
0  2013        China  8541   963315872.0
1  2013  South Korea  8541    22011508.0
2  2013    Singapore  8541    81995028.0
3  2013     Viet Nam  8541       41534.0
4  2013          USA  8541    63834674.0

In [7]:
df_clean['USD_Value_bn']= (df_clean['USD_Value_bn']/1e9)
df_clean.head()

   Year      Partner  Code  USD_Value_bn
0  2013        China  8541      0.963316
1  2013  South Korea  8541      0.022012
2  2013    Singapore  8541      0.081995
3  2013     Viet Nam  8541      0.000042
4  2013          USA  8541      0.063835

In [8]:
total=df_clean.groupby(['Year','Partner'])['USD_Value_bn'].sum().reset_index()

###Creating pivot tables by country

In [9]:
pivot=total.pivot(index='Year', columns='Partner', values='USD_Value_bn').fillna(0)
pivot['total']= pivot.sum(axis=1)
pivot['S.Korea_YoY_change_%']= pivot['South Korea'].pct_change().mul(100).round(2)
pivot['China_YoY_change_%']= pivot['China'].pct_change().mul(100).round(2)
pivot['Singapore_YoY_change_%']= pivot['Singapore'].pct_change().mul(100).round(2)
pivot['Vietnam_YoY_change_%']= pivot['Viet Nam'].pct_change().mul(100).round(2)
pivot['USA_YoY_change_%']= pivot['USA'].pct_change().mul(100).round(2)

###Exporting the data

In [10]:
pivot.to_excel('TradeDataWhole_cleaned.xlsx')